[build.environment]
NODE_VERSION = "18"

[build]
publish = "dist"
command = "pnpm run build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/manifest.webmanifest"
[headers.values]
Content-Type = "application/manifest+json"

[[redirects]]
from = "/"
to = "?lang=en"
status = 302
force = true
conditions = { Language = ["en"] }

[[redirects]]
from = "/"
to = "?lang=ru"
status = 302
force = true
conditions = { Language = ["ru"] }

[[redirects]]
from = "/"
to = "?lang=en"
status = 302
force = true
