// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    GifkiProject: typeof import('./components/GifkiProject.vue')['default']
    MyContacts: typeof import('./components/MyContacts.vue')['default']
    NavigationList: typeof import('./components/NavigationList.vue')['default']
    PhotoPortrait: typeof import('./components/PhotoPortrait.vue')['default']
    ProfileIntro: typeof import('./components/ProfileIntro.vue')['default']
    ProjectItem: typeof import('./components/ProjectItem.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAppBar: typeof import('./components/TheAppBar.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheProfile: typeof import('./components/TheProfile.vue')['default']
    TheProjects: typeof import('./components/TheProjects.vue')['default']
    VBtn: typeof import('vuetify/components')['VBtn']
    VButton: typeof import('vuetify/components')['VButton']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VChip: typeof import('vuetify/components')['VChip']
    VDialog: typeof import('vuetify/components')['VDialog']
    VImg: typeof import('vuetify/components')['VImg']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
  }
}
